### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by NotSoMik** [heditwo/hedibot-two#1]
Hello does the bot update the message when there are more reactions?

**Comment by heditwo** [comment]
Yes I think it does, do you mean the reaction count?Sent from my iPhoneOn Sep 23, 2022, at 7:33 PM, NotSoMik ***@***.***> wrote:﻿
Hello does the bot update the message when there are more reactions?

**Comment by NotSoMik** [comment]
Like if there are 3 reactions the bot says it, if there are 4 reactions the bot edits thr message
